### PR TITLE
Refactor/migration to typescript

### PR DESCRIPTION
**Pull request by samavati**
# Pull Request Description

## Overview

This pull request marks a substantial transformation of the `axios-hooks` repository, with two major objectives:

1. **Migration to TypeScript**: The primary focus of this PR is the migration of the codebase from JavaScript to TypeScript. TypeScript brings several advantages, including enhanced type safety, improved code documentation, and better maintainability. The entire codebase, including core logic, tests, and type definitions, has been transitioned to TypeScript.

2. **Code Refactoring for Improved Readability**: In addition to the TypeScript migration, we've also taken the opportunity to refactor the code to enhance readability and maintainability. This includes:

   - Separating functions into dedicated files: Logic and functions have been organized into separate files, making it easier to find and manage specific parts of the code.
   - Enhanced TypeScript Type Definitions: Type definitions have been added or refined throughout the codebase to provide better type checking and code documentation.
   - Improved Testing: Ensured that all tests were updated and functioning correctly in the TypeScript environment.

## Key Changes

- Migrated the entire codebase from JavaScript to TypeScript, enhancing type safety and code quality.
- Reorganized functions into separate files for better code structure.
- Improved TypeScript type definitions for a more robust development experience.
- Verified that all tests are working as expected in the TypeScript environment.

## Additionally TSDocs added

- Added TSDoc comments to methods, functions, and properties, providing detailed descriptions of their usage and parameters.
- Improved code documentation by using standardized TSDoc formatting, which is easily parsed by IDEs and code editors.

```typescript
/**
 * Executes the request and dispatches the appropriate actions.
 * @param config - The request config to pass to axiosInstance.
 * @param dispatch - The dispatch function.
 * @param cache - The cache.
 * @param axiosInstance - The axios instance.
 * @returns A Promise representing the response.
 * @throws {Error} - An error if the request fails.
 * @internal
 */
export async function executeRequest(
  config: AxiosRequestConfig,
  dispatch: Dispatch,
  cache: UseAxiosCache,
  axiosInstance: AxiosInstance
): Promise<UseAxiosResponse> {
  // Function implementation
}
```

Screenshot 2023-10-27 at 7 32 20 PM

## Why This PR?

This PR is crucial for the long-term maintainability and reliability of the `axios-hooks` library. By migrating to TypeScript, we ensure that the codebase remains free of type-related bugs and provides better code documentation. The code reorganization further simplifies understanding and contributing to the project.

## Testing

All existing tests have been reviewed and updated to ensure they pass in the TypeScript environment. Additionally, new TypeScript-specific tests have been added where necessary to maintain code integrity.

## Closing Note

This PR represents a significant step forward for the `axios-hooks` library, both in terms of technology and code organization. Your feedback and review are greatly appreciated as we continue to improve and expand the capabilities of this library.

### CODE REVIEW

**Comment by samavati** [comment]
Hi @simoneb
Could you please check this PR? it seems the workflow needs an approval
Thanks

**Comment by simoneb** [comment]
This PR contains too many changes. I would recommend that you split it so that one part contains only the typescript migration, and the other only the refactoring.

**Comment by samavati** [comment]
> This PR contains too many changes. I would recommend that you split it so that one part contains only the typescript migration, and the other only the refactoring.

Good point
Will do that

**Comment by samavati** [comment]
I am closing this since we are going to do the migration gradually

**Pull request closed without merging**
