### PR TITLE
perf: initialize error to null in state to avoid additional render

### PR DESCRIPTION
**Pull request by simoneb**

### CODE REVIEW

**Comment by Songkeys** [comment]
Sorry for this untested PR...

Seems that it's still rendering 3 times in `1.10.1`...

I found this: https://stackoverflow.com/questions/54927622/usestate-do-double-render

> it's an intentional feature to help you to detect unexpected side effects if you're using StrictMode

Guess we'll be fine in production env. We can ignore the "double renders".

**Comment by simoneb** [comment]
Yes I noticed that too, there is no way around the 3 renders:

- first render
- render with request starts
- render when request completes

I published this change anyway because it kinda makes sense that error doesn't change to undefined to null, but I'm considering whether the initial state should really be `loading: true`, since the request has not even started yet. But it's too big a change to make it in a patch release and hard to predict which kind of consequences it may have

**Comment by Songkeys** [comment]
I think the `loading` should be as an indicator for UI to show <Loading /> status. I can't think of any scenery that developers should pay attention to the real network status after they called the literal "request" method.

Some other libraries also don't distinct these statuses:

- https://github.com/tannerlinsley/react-query#returns
- https://github.com/vercel/swr#return-values
- https://use-http.com/#/?id=basic-usage-auto-managed-state

**Comment by simoneb** [comment]
The rationale for initializing loading to true (when the request is not manual) when I initially designed this hook is that the hook returns an object like this:

`[{ data, loading, error }, ...]`

and I liked the idea that you get either of the three:

- either it's loading
- or it's an error
- and if it's neither of the above, then it must mean that you have data

If loading wasn't initialized to true when the hook is rendered the first time, you would have that before the request starts you'd have:

- loading false
- error falsy
- data falsy

leading to requiring more conditionals in the code to handle the initial state.

This is not necessarily the _right_ decision, but it's an intentional design choice that can't easily be reverted because user code is probably relying on this behavior.

I hope it makes sense.

**Comment by Songkeys** [comment]
I got your idea.

I think the only fit scene for initializing loading to false is "manually request"? But not other APIs that "seems" sending request immediately. Otherwise, it'd be confusing whether or not to show loading status on the UI unless writing more code.

Alternatively, we can add a `status` property in the object that gives the real status, with enum values like "ready", "fetching", "fetched", "error"... This would be more explicit and clearer. But more verbose.

**Comment by simoneb** [comment]
I think the loading flag is good enough for most scenarios, so unless there are requests for a finer grained control over the status I'll keep it as it is.

**Pull request merged**
