### PR TITLE
fix: missing canceltoken in refetch

### PR DESCRIPTION
**Pull request by menostos**

### CODE REVIEW

**Comment by menostos** [comment]
Sorry for the "fast" PR. I was using axios-hooks together with unstated-next and the useEffect hook. I created a unstated Container with an manual useAxios and exposed the load method using the Container. Using the load method in the component in a useEffect caused an error.
Here is the codesandbox https://codesandbox.io/s/gracious-williams-ufzgm
I  am not quite sure what's going on here, no am I sure, it should be done this way.
I would appreciate if you could look into this, if this should be even supported.

**Comment by simoneb** [comment]
Thanks for the details. Indeed if the useEffect hook used by axios-hooks never runs you will not have a cancel token, but I don't understand why that would happen apart from a SSR scenario, in which I wouldn't expect the manual refetch function to be called anyway.

I'll look into this to see if it's a case that we should handle, in which case I'm ok with your fix but I would be grateful if you could include tests.

**Comment by menostos** [comment]
I did some analyzing on the problem. The problem comes from the fact, that useEffect is processed from the lowest component to the highest component. This makes sense since it's "like" componentDidMount. Know using the ContextApi togehter with hooks, messes things up since it's always at least one level higher than where it gets consumed. This resolves into the useCallback being called before the useEffect from axios-hooks. So the cancelToken is not yet available.

**Comment by simoneb** [comment]
Thanks for the additional details. I had a chance to take a look at your code example, and I'm wondering, why are you calling load in that useEffect hook in the first place? It works just fine without.

**Comment by menostos** [comment]
Yes it's probably bad design from my side. I was using props from the component to to load different urls using the axios-hooks refetch method and wanted additional logic built into the unstated container.

**Comment by simoneb** [comment]
I still don't quite understand why the hook useAxios hasn't been called yet when you call refetch, it looks like it's a change in behavior introduced by unstated-next, which is somewhat surprising. I'm wondering if it would cause issues with other hooks too. 

I mean, if I have a component that's using hook A _then_ useEffect, and hook A is using hook B which is using useEffect, I would expect the useEffect used by hook B to execute before the useEffect hook used by my component, because that's the order of invocation. I'm not actually sure this is an invariant that React enforces, but you can see in [this modified example](https://codesandbox.io/s/wandering-water-4jjdk) that removing the unstated-next code while still wrapping useAxios in your custom hook works fine, meaning that the useAxios' useEffect hook is executed before the App.jsx useEffect hook, which is the expected behavior. 

So, I'm tempted to think that unstated-next is modifying the behavior of hooks in some way that doesn't really look safe.

**Comment by menostos** [comment]
Ok, I think I get it. The useAxios is called within the React/Unstated Provider which is above the Component using the data. So the component using the data gets the refetch method from above and then invokes it in useEffect before the Provider executes it's useEffect.

**Comment by simoneb** [comment]
That's a great analysis! Still, I'm not sure that what that library is doing is completely legitimate, even though I can't think of an example where such behavior would break other assumptions. Interesting find though, but I'm not sure this library should handle such an edge case, it would be a change we'd do to cover a scenario that we're not even sure should really happen. What do you think?

**Comment by menostos** [comment]
It's probably bad design. I mean it's passing a function to a child component which invokes it with another function as parameter and that function gets immediatly executed by the parent component. This does not really feels like the React way. So maybe just ignore it or print a message to other devs.

**Comment by simoneb** [comment]
I will close this pull request because it doesn't feel like this behavior is generic enough to require a specific implementation, but thanks a lot for bringing this up and for analyzing the issue.

**Pull request closed without merging**
